name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: StarbuckBarista/github-activity-readme@testing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          HTML_ENCODING: "true"
          COMMIT_MSG: ":zap: Updated Recent Activity"
          MAX_LINES: 10
