name: Update Profile README

permissions:
  contents: write

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Action Code
        uses: actions/checkout@v3
        with:
          repository: StarbuckBarista/profile-activity
          ref: master
          path: updater

      - name: Install Action Dependencies
        working-directory: updater/action
        run: npm ci

      - name: Run Activity Updater
        uses: ./updater/action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Chore: Update Activity" || echo "No Changes to Commit"
          git push
